# Generated by Django 3.2.6 on 2021-08-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Ciencia y Arte', 'CIENCIA Y ARTE'), ('Historia', 'HISTORIA'), ('Deportes', 'DEPORTES'), ('Geografia', 'GEOGRAFÍA'), ('Economia', 'ECONOMÍA'), ('Ciencia y Educacion', 'CIENCIA Y EDUCACIÓN'), ('Entretenimiento', 'ENTRETENIMIENTO')], max_length=150)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=200)),
                ('max_preguntas', models.IntegerField()),
                ('tiempo_limite', models.IntegerField(help_text='duración del cuestionario')),
                ('puntaje_para_aprobar', models.IntegerField(help_text='puntaje requerido')),
                ('dificultad', models.CharField(choices=[('fácil', 'FÁCIL'), ('intermedio', 'INTERMEDIO'), ('difícil', 'DIFÍCIL')], max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionario.categoria')),
            ],
        ),
    ]
