# Generated by Django 3.2.6 on 2021-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Cultura y Arte', 'CULTURA Y ARTE'), ('Historia', 'HISTORIA'), ('Deportes', 'DEPORTES'), ('Geografia', 'GEOGRAFÍA'), ('Economia', 'ECONOMÍA'), ('Ciencia y Educacion', 'CIENCIA Y EDUCACIÓN'), ('Entretenimiento', 'ENTRETENIMIENTO')], max_length=150),
        ),
    ]
