# Generated by Django 3.2.6 on 2021-08-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_auto_20210826_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='resultado',
            name='preguntas',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='respuestas',
            field=models.TextField(null=True),
        ),
    ]
